export const TEMPLATE_ACTION_TYPE = 'TEMPLATE_ACTION_TYPE';

export const UPDATE_CURRENT_CITY = 'UPDATE_CURRENT_CITY';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const UPDATE_USER_PROFILE_DATA = 'UPDATE_USER_PROFILE_DATA';

export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

export const UPDATE_USER_JWT_DATA = 'UPDATE_USER_JWT_DATA';