export const TEMPLATE_ACTION_TYPE = 'TEMPLATE_ACTION_TYPE';

export const UPDATE_CURRENT_CITY = 'UPDATE_CURRENT_CITY';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";