export const TEMPLATE_ACTION_TYPE = 'TEMPLATE_ACTION_TYPE';

export const UPDATE_CURRENT_CITY = 'UPDATE_CURRENT_CITY';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const UPDATE_USER_PROFILE_DATA = 'UPDATE_USER_PROFILE_DATA';

export const USER_LOG_OUT = 'USER_LOG_OUT'

export const UPDATE_USER_JWT_DATA = 'UPDATE_USER_JWT_DATA';

export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';

export const ADD_ORDERED_MENU_ITEM = 'ADD_ORDERED_MENU_ITEM';

export const REMOVE_ORDERED_MENU_ITEM = 'REMOVE_ORDERED_MENU_ITEM';

export const EMPTY_CURRENT_ORDER = "EMPTY_CURRENT_ORDER";

export const UPDATE_LIST_USER_ORDERS = "UPDATE_LIST_USER_ORDERS";

export const UPDATE_LIST_USER_CATHERING_ORDERS = "UPDATE_LIST_USER_CATHERING_ORDERS"

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

export const UPDATE_USER_FAVORITE_PLACES = 'UPDATE_USER_FAVORITE_PLACES';

export const USER_FAVORITE_PLACES = 'USER_FAVORITE_PLACES';
